### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by irigone** [asiekierka/funscii#5]
I want an AUR package so that I (or someone else) could install the font
Can you do it? I never wrote pkgbuilds honestly, but I can try

**Comment by irigone** [comment]
Also I like your pfp

**Comment by asiekierka** [comment]
>Can you do it? I never wrote pkgbuilds honestly, but I can try

I don't think I could put the effort into adequately maintaining it at this time, so no, sorry. The font expansion was made with software/game development in mind - for home usage, unscii combined with GNU's Unifont might be a better choice.

>Also I like your pfp

Thanks!
